name: Build libdwarf natives

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  # Which libdwarf tag/branch to build
  LIBDWARF_VERSION: v0.12.0

# ──────────────────────────────────────────────────────────────────────────────
# L I N U X
# ──────────────────────────────────────────────────────────────────────────────
jobs:
  build-linux:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      # ---------- cache ------------------------------------------------------
      - id: cache-linux
        uses: actions/cache@v4
        with:
          path: .cache/libdwarf
          key: libdwarf-linux-${{ env.LIBDWARF_VERSION }}

      # ---------- toolchain --------------------------------------------------
      - name: Install toolchain
        if: steps.cache-linux.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update -y
          sudo apt-get install --no-install-recommends -y \
            build-essential cmake ninja-build pkg-config \
            zlib1g-dev libzstd-dev

      # ---------- build ------------------------------------------------------
      - name: Build shared library
        if: steps.cache-linux.outputs.cache-hit != 'true'
        run: |
          git clone --depth 1 --branch "$LIBDWARF_VERSION" \
              https://github.com/davea42/libdwarf-code libdwarf-code

          cmake -S libdwarf-code -B build -G Ninja \
                -DCMAKE_BUILD_TYPE=Release \
                -DBUILD_SHARED=YES  -DBUILD_NON_SHARED=NO \
                -DCMAKE_INSTALL_PREFIX="$PWD/install"

          cmake --build build --target install --parallel

          WRAP=jna-wrapper/src/main/resources/linux-x86-64
          mkdir -p "$WRAP" out .cache/libdwarf/linux
          cp install/lib/libdwarf*.so* "$WRAP/"
          cp install/lib/libdwarf*.so* out/
          cp install/lib/libdwarf*.so* .cache/libdwarf/linux/

      # ---------- copy from cache (hit) --------------------------------------
      - name: Copy cached .so files
        if: steps.cache-linux.outputs.cache-hit == 'true'
        run: |
          WRAP=jna-wrapper/src/main/resources/linux-x86-64
          mkdir -p "$WRAP" out
          cp .cache/libdwarf/linux/* "$WRAP"/
          cp .cache/libdwarf/linux/* out/

      # ---------- artifact ---------------------------------------------------
      - uses: actions/upload-artifact@v4
        with:
          name: libdwarf-linux
          path: out/*

# ──────────────────────────────────────────────────────────────────────────────
# W I N D O W S
# ──────────────────────────────────────────────────────────────────────────────
  build-windows:
    runs-on: windows-2022
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: actions/checkout@v4

      # ---------- MSYS2 ------------------------------------------------------
      - name: MSYS2 setup
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-zlib
            git

      # ---------- cache ------------------------------------------------------
      - id: cache-win
        uses: actions/cache@v4
        with:
          path: .cache/libdwarf
          key: libdwarf-windows-${{ env.LIBDWARF_VERSION }}

      # ---------- build ------------------------------------------------------
      - name: Build shared library
        if: steps.cache-win.outputs.cache-hit != 'true'
        run: |
          git clone --depth 1 --branch "$LIBDWARF_VERSION" \
              https://github.com/davea42/libdwarf-code libdwarf-code

          cmake -S libdwarf-code -B build -G Ninja \
                -DCMAKE_BUILD_TYPE=Release \
                -DBUILD_SHARED=YES  -DBUILD_NON_SHARED=NO \
                -DCMAKE_INSTALL_PREFIX="$PWD/install"

          cmake --build build --target install --parallel

          WRAP=jna-wrapper/src/main/resources/win32-x86-64
          mkdir -p "$WRAP" out .cache/libdwarf/windows
          cp install/bin/libdwarf*.dll "$WRAP/"
          cp install/bin/libdwarf*.dll out/
          cp install/bin/libdwarf*.dll .cache/libdwarf/windows/

      # ---------- copy from cache (hit) --------------------------------------
      - name: Copy cached DLLs
        if: steps.cache-win.outputs.cache-hit == 'true'
        run: |
          WRAP=jna-wrapper/src/main/resources/win32-x86-64
          mkdir -p "$WRAP" out
          cp .cache/libdwarf/windows/* "$WRAP"/
          cp .cache/libdwarf/windows/* out/

      # ---------- artifact ---------------------------------------------------
      - uses: actions/upload-artifact@v4
        with:
          name: libdwarf-windows
          path: out/*

# ──────────────────────────────────────────────────────────────────────────────
# P U B L I S H
# ──────────────────────────────────────────────────────────────────────────────
  publish:
    needs: [build-linux, build-windows]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04

    # allow the workflow to push to the repo
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0          # we will commit / push back

      - uses: actions/download-artifact@v4
        with:
          path: _artifacts

      # ---------- copy into wrapper, but only if binary really changed -------
      - name: Copy binaries into wrapper resources
        run: |
          set -euo pipefail
          copy_if_changed() {
            src="$1"; dest="$2"
            [ -e "$src" ] || return 0
            mkdir -p "$(dirname "$dest")"
            if [ -f "$dest" ] && cmp -s "$src" "$dest"; then
              echo "Unchanged: $dest"
            else
              cp "$src" "$dest"
              echo "Updated:   $dest"
            fi
          }

          find _artifacts/libdwarf-linux   -type f -print0 | \
            while IFS= read -r -d '' f; do
              rel=${f#*_artifacts/libdwarf-linux/}
              copy_if_changed "$f" \
                "jna-wrapper/src/main/resources/linux-x86-64/$rel"
            done

          find _artifacts/libdwarf-windows -type f -print0 | \
            while IFS= read -r -d '' f; do
              rel=${f#*_artifacts/libdwarf-windows/}
              copy_if_changed "$f" \
                "jna-wrapper/src/main/resources/win32-x86-64/$rel"
            done

      # ---------- commit & push (only if changed) ----------------------------
      - name: Commit & push (only if changed)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add jna-wrapper/src/main/resources || true

          if git diff --cached --quiet; then
            echo "No shared-library updates to commit."
            exit 0
          fi

          git commit -m "Update pre-built libdwarf libraries to ${LIBDWARF_VERSION}"
          git push origin HEAD
