# .github/workflows/build-libdwarf-jar.yml
name: Build libdwarf JNA jar

on:
  workflow_run:
    workflows: ["Build libdwarf natives"]
    types: [completed]
  workflow_dispatch:

jobs:
# --------------------------------------------------------------------------- #
#  B U I L D   J A V A                                                        #
# --------------------------------------------------------------------------- #
  build-java:
    if: github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Package libdwarf.jar
        run: mvn -B -ntp package -DskipTests

      - uses: actions/upload-artifact@v4
        with:
          name: libdwarf-jna
          path: target/libdwarf.jar

# --------------------------------------------------------------------------- #
#  P U B L I S H   ( copy into repo & commit if changed )                     #
# --------------------------------------------------------------------------- #
  publish-jar:
    needs: build-java
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04

    permissions: { contents: write }

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/download-artifact@v4
        with:
          name: libdwarf-jna
          path: _jar

      - name: Copy JAR into src directory
        run: |
          mkdir -p src
          cp _jar/libdwarf.jar src/

      - name: Commit & push (only when changed)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add src/libdwarf.jar || true

          if git diff --cached --quiet; then
            echo "No JAR changes to commit."
            exit 0
          fi

          git commit -m "Update shaded libdwarf.jar"
          git push origin HEAD
